#!/bin/sh
# live-build configuration script
# see 'man lb config'
export projectname="autodebian"
export projectversion="1.4"

lb config noauto \
--apt-recommends false \
--architectures amd64 \
--archive-areas 'main contrib non-free' \
--backports true \
--security true \
--updates true \
--source false \
--binary-filesystem ext4 \
--binary-images iso-hybrid \
--checksums sha256 \
--clean \
--debconf-frontend dialog \
--debian-installer live \
--debian-installer-distribution stretch \
--debian-installer-gui true \
--debootstrap-options "--include=apt-transport-https,ca-certificates,openssl" \
--distribution stretch \
--firmware-binary true \
--firmware-chroot true \
--initramfs live-boot \
--iso-publisher dbu \
--iso-volume autodebian-1.2 \
--linux-packages "linux-image linux-headers" \
--bootappend-live "boot=live config" \
--memtest memtest86+ \
--win32-loader true

"${@}"
