#!/bin/bash
set -e
cd config/package-lists/
echo "#This file is automatically generated" >| ../../ansible/tasks/packages.yml
for i in [a-z]*chroot; do
    taskname="- name: packages - install $i";
    pkgs=$(egrep "^([a-z]|[0-9])" "$i");
    echo $taskname;
    echo "  apt: state=latest pkg={{ item }}";
    echo "  with_items:";
    for pkg in $pkgs; do
        echo "    - $pkg";
    done;
    echo;
done >> ../../ansible/tasks/packages.yml
